### ISSUE TITLE
Unquoted certificate name results in unknown exception

### ISSUE THREAD

**Issue by ChrisLMerrill** [dg76/signpackage#1]
Ran into this problem which resulted in "unknown exception" messages from every step. I noticed that the certificate name was not quoted (and contains spaces).

So I added quotes around the sign-key parameter, like this:
    command.add("\"" + cmd.getOptionValue(OPTION_SIGN_KEY) + "\"")

and this resolved the problem (I think).

Now I get "no identity found" errors, but I presume (hope) that is a different problem.

Thanks in advance for this tool and your article. I feel like I might actually get this working :)

**Comment by dg76** [comment]
Hi!

I am glad that you like this tool! :-) However the change that you suggest is wrong, because what the program outputs is not what it actually runs. If I implement your change, I get "no identity found" for each command because the key name is wrong, it now contains the quotation marks and thus cannot be found.

This is the code:

```
        val command = ArrayList<String>()
        command.add("codesign")
        if (cmd.hasOption(OPTION_TIMESTAMP)) command.add("--timestamp")
        if (cmd.hasOption(OPTION_RUNTIME)) command.addAll(listOf("--options", "runtime"))
        if (cmd.hasOption(OPTION_ENTITLEMENTS)) command.addAll(listOf("--entitlements", File(cmd.getOptionValue(OPTION_ENTITLEMENTS)).absolutePath))
        command.addAll(listOf("--deep", "-vvv", "-f"))
        command.add("--sign")
        command.add(cmd.getOptionValue(OPTION_SIGN_KEY))
        command.add(dylibFile.absolutePath)

        println(command.joinToString(" "))

        ProcessBuilder()
                .directory(dylibFile.parentFile)
                .inheritIO()
                .command(command)
                .start()
                .waitFor()
```

As you can see it prints the command by just concatenating the command line parameters. However when actually executing the command using the ProcessBuilder, it passes a "List" to the ProcessBuilder (`"command(command)"`). So the ProcessBuilder knows where each parameter ends and does not have to rely on quotation marks. So the code seems to be fine. However when running the codesign commands manually, you have to add the quotation marks, because you have no way to pass a "List" of parameters to your shell.

Which error do you get when running the same codesign command yourself (with quotation marks)?

**Comment by ChrisLMerrill** [comment]
Ok, then. Thanks.


```
chris@Chriss-Mac-mini install % java -jar ../../signpackage/SignPackage.jar -d build/mac-image -t -r -k "Developer ID Application: Christopher Merrill (B6UNNAD3HL)" -e "package/macos/app.entitlements"
/Users/chris/dev/museide-closed/install/build/mac-image/MuseIDE.app/Contents/MacOS/MuseIDE
codesign --timestamp --options runtime --entitlements /Users/chris/dev/museide-closed/install/package/macos/app.entitlements --deep -vvv -f --sign Developer ID Application: Christopher Merrill (B6UNNAD3HL) /Users/chris/dev/museide-closed/install/build/mac-image/MuseIDE.app/Contents/MacOS/MuseIDE
unknown exception
```

Runtime environment is:

```
chris@Chriss-Mac-mini install % java --version
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
chris@Chriss-Mac-mini install % 
```

I guess I'll need to run in the debugger to get the exception.

**Comment by ChrisLMerrill** [comment]
I thought the "unknown exception" was coming from SignPackage, but it is coming from code sign. When I run the one of the commands output from SignPackage (with quotes around the certificate name), I get the same result in the terminal :(

```
chris@Chriss-Mac-mini install % codesign --timestamp --options runtime --entitlements /Users/chris/dev/museide-closed/install/package/macos/app.entitlements --deep -vvv -f -s "Developer ID Application: Christopher Merrill (B6UNNAD3HL)" /Users/chris/dev/museide-closed/install/build/mac-image/MuseIDE.app/Contents/runtime/Contents/Home/lib/libosxapp.dylib 
unknown exception
chris@Chriss-Mac-mini install % 
```

If you have any ideas what I'm doing wrong, let me know. Otherwise, I guess I'm back to square one :(

**Comment by dg76** [comment]
Unfortunately I don't know what causes codesign to display "unknown exception". Have you tried to reduce the entitlements to a minimum as a test? A simple entitlements file could look like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.security.app-sandbox</key>
        <false/>
        <key>com.apple.security.network.server</key>
        <true/>
        <key>com.apple.security.network.client</key>
        <true/>
        <key>com.apple.security.files.user-selected.read-write</key>
        <true/>
        <key>com.apple.security.cs.allow-jit</key>
        <true/>
        <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
        <true/>
        <key>com.apple.security.cs.disable-executable-page-protection</key>
        <true/>
        <key>com.apple.security.cs.disable-library-validation</key>
        <true/>
        <key>com.apple.security.cs.allow-dyld-environment-variables</key>
        <true/>
    </dict>
</plist>
```

Can you sign other files with the same command? So that the problem might be in the dylib file?

**Comment by ChrisLMerrill** [comment]
It was failing on all files. But, you've solved it for me!  I had copied the example entitlements from your blog post...but that is only a part of the file. Seems kinda obvious looking at it now, but at the time, I just copied that into a file. So the problem was an invalid entitlements file. 

Now your signpackage has signed all the files with no errors. After running the other steps in your post and following the notarization and stapling steps at http://www.zarkonnen.com/signing_notarizing_catalina, I now have an app that successfully installs on Catalina!

Thanks a bunch. In my book, you've officially "paid it forward" today!

Now comes the fun of getting this whole process documented and automated for the two projects my users are waiting on a Mac installer :)

**Comment by dg76** [comment]
Great, I am glad that it worked now! I have added a complete example of an entitlements file to my webpage https://blog.dgunia.de/2020/02/12/signed-macos-programs-with-java-14/ now to prevent other users from making the same mistake. :-) Thank you for telling me the reason for the problem!
