### ISSUE TITLE
-x parameter not documented

### ISSUE THREAD

**Issue by janosvitok** [dg76/signpackage#2]
[Here](https://github.com/dg76/signpackage/blob/master/src/main/java/com/dgunia/signpackage/Main.kt#L33) the documentation is copied from other parameter and [here](https://github.com/dg76/signpackage/blame/master/README.md#L17) it is completely missing.

**Comment by dg76** [comment]
Thank you very much for reporting this problem! I have fixed it in both places now. :-)
