### ISSUE TITLE
jnilib files should be also signed

### ISSUE THREAD

**Issue by japplis** [dg76/signpackage#7]
Line 82 of Main.kt
is
`} else if (file.name.endsWith(".dylib") || file.canExecute()) {`
should be
`} else if (file.name.endsWith(".dylib") || file.name.endsWith(".jnilib") || file.canExecute()) {`

Let me know if you want a merge request.

**Comment by dg76** [comment]
Thank you, I have added it now! :-)

**Comment by japplis** [comment]
You're welcome!
So that you know this bug fix just helped me to sign (and notarize) my open source Java office suite based on NetBeans platform: https://github.com/Japplis/Joeffice

**Comment by dg76** [comment]
Wow that looks like a huge project! 😬😊 I am glad that my small tool here was useful for you! Thank you very much for sending this fix! 😊
